
#include "stdafx.h"
#include "SketchupHelper.h"
#include <fstream>

#include <Windows.h>

string currentDir() {
	char buffer[500];
	GetCurrentDirectoryA(500,buffer);
	return buffer;
}

void makeDir(string dir) {
	CreateDirectoryA(dir.c_str(),NULL);
}

SketchupHelper::SketchupHelper() {
	SUInitialize();
	m_outputDir = currentDir()+ "/";
}

void SketchupHelper::setOutputDir(const string& dir) {
	m_outputDir = currentDir() + "/" + dir + "/";
	makeDir(currentDir() + "/" + dir);
	cout << "Output directory is " << m_outputDir << endl;
}

void SketchupHelper::exportMaterials(const string& filename) {
	size_t count =0;
	SUModelGetNumMaterials(m_Model,&count);
	vector<SUMaterialRef> materials(count);
	SUModelGetMaterials(m_Model,count,&materials[0],&count);

	ofstream mtlFile(m_outputDir+filename);

	for(size_t i=0; i < count; i ++) {
		cout << "Writing: " << materialName(materials[i]) << endl;
		mtlFile << "newmtl " << materialName(materials[i]) << endl;
		
		mtlFile << "illium 4" << endl;

		SUColor ambient;
		SUMaterialGetColor(materials[i],&ambient);
		mtlFile << "Ka " << (ambient.red / 255.0f) << " " << (ambient.green/255.0f) << " " << (ambient.blue/255.0f) << endl; 
				
		SUTextureRef tex = SU_INVALID;
		if(SUMaterialGetTexture(materials[i],&tex) == SU_ERROR_NONE) {
			SUStringRef fileName = SU_INVALID;
			SUStringCreate(&fileName);
			if(SUTextureGetFileName(tex,&fileName) == SU_ERROR_NONE) {
				string f = fromSUString(fileName);
				SUTextureWriteToFile(tex,(m_outputDir+f).c_str());

				mtlFile << "Tf 1.00 1.00 1.00" << endl;
				//mtlFile << "map_Ka " << f << endl;
				mtlFile << "map_Kd " << f << endl;

				mtlFile << "Ni 1.00" << endl;
				mtlFile << "Ks 1.00 1.00 1.00" << endl;
				mtlFile << "Ns 0.00" << endl;
			}
		} else {
			
			mtlFile << "Kd " << (ambient.red / 255.0f) << " " << (ambient.green/255.0f) << " " << (ambient.blue/255.0f) << endl; 
		
		}
	}
}

string SketchupHelper::fromSUString(SUStringRef str) {
	size_t len;
	SUStringGetUTF8Length(str,&len);

	char buff[300] = {0};
	SUStringGetUTF8(str,300,buff,&len);
	return buff;
}

string SketchupHelper::materialName(SUMaterialRef mat) {
	/*SUStringRef str = SU_INVALID;
	SUStringCreate(&str);
	SUResult res =SUMaterialGetName(mat,&str);
	if(res == SU_ERROR_NONE) {
		return fromSUString(str);
	}*/

	char buf[20];
	return itoa((int)mat.ptr,buf,16);
}

bool SketchupHelper::openFile(const string& filename) {
	SUModelRef newModel = SU_INVALID;
	SUResult res = SUModelCreateFromFile(&newModel, filename.c_str());
	if (res != SU_ERROR_NONE){

		return false;
	}

	m_Model=newModel;

	
	SUModelUnits units;
	SUModelGetUnits(m_Model,&units);

	switch(units){
	case SUModelUnits_Inches:
		m_Scale = 39.3700787;
		break;
	case SUModelUnits_Feet:
		m_Scale = 3.2808399;
		break;
	case SUModelUnits_Millimeters:
		m_Scale= 1000.0f;
		break;
	case SUModelUnits_Centimeters:
		m_Scale= 100.0f;
		break;
	case SUModelUnits_Meters:
		m_Scale= 1.0f;
		break;
	}

	m_Scale *= 40;

	return true;
}


bool SketchupHelper::exportHull(const string& filename) {
	// Get the entity container of the model.
	SUEntitiesRef entities = SU_INVALID;
	SUModelGetEntities(m_Model, &entities);
	// Get all the faces from the entities object
	size_t faceCount = 0;
	SUEntitiesGetNumFaces(entities, &faceCount);
	
	if (faceCount == 0) {
		cerr << "Model has no faces :(";
		return false;
	}
		
	cout << "Model has " << faceCount << " faces" << endl;

	ofstream objFile;
	objFile.open(m_outputDir+filename);
	
	objFile << "# File generated by sketchup2room" << endl;

	objFile << "mtllib materials.mtl" << endl;

	int cumlativeVerticies = 1;
	vector<int> vertexStart(faceCount);
	vector<SUFaceRef> faces(faceCount);
	vector<SUMeshHelperRef> faceMeshes(faceCount);
	
	SUEntitiesGetFaces(entities, faceCount, &faces[0], &faceCount);
	

	//Generate meshes
	for(size_t i=0; i < faceCount; i++) {
		SUMeshHelperCreate(&faceMeshes[i],faces[i]);
	}

	//Ouput Vertices
	for(size_t i=0; i < faceCount; i++) {
		objFile << "# Verts for Face " << i << endl;

		size_t vertexCount = 0;
		SUMeshHelperGetNumVertices(faceMeshes[i],&vertexCount);
		
		vector<SUPoint3D> verts(vertexCount);
		SUMeshHelperGetVertices(faceMeshes[i],vertexCount,&verts[0],&vertexCount);
		
		vector<SUVector3D> normals(vertexCount);
		SUMeshHelperGetNormals(faceMeshes[i],vertexCount,&normals[0],&vertexCount);
		
		vector<SUPoint3D> tcs(vertexCount);
		SUMeshHelperGetFrontSTQCoords(faceMeshes[i],vertexCount,&tcs[0],&vertexCount);


		for(size_t j=0; j < vertexCount; j++) {
			objFile << "v " << verts[j].x / m_Scale << " " << verts[j].y / m_Scale << " " << verts[j].z / m_Scale << endl;
			objFile << "vt " << tcs[j].x << " " << tcs[j].y << endl;
			objFile << "vn " << normals[j].x << " " << normals[j].y << " " << normals[j].z << endl;
		}
		
		vertexStart[i] = cumlativeVerticies;
		cumlativeVerticies += vertexCount;
	}

	for(size_t i=0; i < faceCount; i++) {
		
		size_t triCount = 0;
		SUMeshHelperGetNumTriangles(faceMeshes[i],&triCount);

		size_t gotIndices = 0;
		vector<size_t> indicies(triCount*3);
		SUResult res = SUMeshHelperGetVertexIndices(faceMeshes[i],triCount*3,&indicies[0],&gotIndices);
		assert(res == SU_ERROR_NONE);
		
		size_t s = vertexStart[i];

		objFile << "# Face " << i << endl;

		SUMaterialRef mat = SU_INVALID;
		SUFaceGetFrontMaterial(faces[i],&mat);

		objFile << "usemtl " << materialName(mat) << endl;

		for(size_t j=0; j < triCount; j++) {
		
			objFile << "f ";
			objFile << (s + indicies[(j*3)+0]) << "/" << (s + indicies[(j*3)+0]) << "/" << (s + indicies[(j*3)+0])<< " ";
			objFile << (s + indicies[(j*3)+1]) << "/" << (s + indicies[(j*3)+1]) << "/" << (s + indicies[(j*3)+1]) << " ";
			objFile << (s + indicies[(j*3)+2]) << "/" << (s + indicies[(j*3)+2]) << "/" << (s + indicies[(j*3)+2]) << endl;
		}

		objFile << endl;
	}

	return true;
}

void SketchupHelper::writeHtmlFile(const string& htmlFile, const string& fileName) {

	ofstream html(m_outputDir+htmlFile);


	html << "<html>" << endl;
	html << "<head>" << endl;
	html << "<title>SketchUp Room - " << fileName << "</title>" << endl;
	html << "</head>" << endl;
	html << "<body>" << endl;
	html << "<FireBoxRoom>" << endl;
	html << "<Assets>" << endl;
	html << "<AssetObject id=\"hull\" src=\"" << fileName << ".obj\" mtl=\"" << fileName <<".mtl\" />" << endl;
	html << "</Assets>" << endl;
	html << "<Room>" << endl;
	html << "<Object id=\"hull\" collision_id=\"hull\" locked=\"true\" pos=\"0 0 0\" xdir\=\"-1 0 0\" ydir=\"0 0 1\" zdir=\"0 1 0\" col=\"0.2 0.3 0.2\" />" << endl;
	html << "</Room>" << endl;
	html << "</FireBoxRoom>" << endl;
	html << "</body>" << endl;
	html << "</html>" << endl;

	html.close();
}